[workspace]
members = [
  "apt2aptly",
  "obs2aptly",
  "sync2aptly",
  "aptlyctl",
  "aptly-rest",
  "aptly-rest-mock",
  "aptly-latest-snapshots"
]
resolver = "2"

[workspace.dependencies]
# We need the fixes in https://github.com/indygreg/linux-packaging-rs/pull/27 (merged)
# And reqwest updates from https://github.com/indygreg/linux-packaging-rs/pull/35 (pending)
debian-packaging = { git = "https://github.com/collabora/linux-packaging-rs.git", rev = "24c125c39f4345bf269574e2774dd0691ad54c1f" }
