[package]
name = "aptly-rest-mock"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http-types = "2.12.0"
serde = "1.0.137"
serde_json = "1.0.81"
url = "2.2.2"
wiremock = "0.5.13"
