name: test suite
on:
  push:
    tags:
      - '*'
    branches-ignore:
      - "gh-readonly-queue/**"
  pull_request:
  merge_group:

env:
  REGISTRY: ghcr.io
  IMAGE_REPOSITORY: ${{ github.repository }}

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-targets --all-features

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            components: rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            components: clippy
            # Pin clippy, so that new lints don't break the build.
            toolchain: '1.87.0'
      - run: cargo clippy --all-targets -- -D warnings

  docker-image:
    name: Docker image build
    runs-on: ubuntu-latest
    needs:
    - test
    - fmt
    - clippy

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - IMAGE_NAME: latest-snapshots
          - IMAGE_NAME: cli

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            # set latest tag for default branch
            # see https://github.com/docker/metadata-action#latest-tag
            type=raw,value=latest,enable={{is_default_branch}}
            # add a unique tag for each workflow run
            type=sha,prefix=ci-${{ github.run_id }}-,format=short
            # then follow the default behavior
            # see https://github.com/docker/metadata-action#tags-input
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
          images: |
            # this one is just for backward compatibility (April 2025)
            name=${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }},enable=${{ matrix.IMAGE_NAME == 'latest-snapshots' }}
            # use this one
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ matrix.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.${{ matrix.IMAGE_NAME }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  allgreen:
    if: always()
    needs:
    - test
    - fmt
    - clippy
    - docker-image
    runs-on: Ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
